# Generated by Django 5.1.3 on 2024-12-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_review_product_remove_review_user_orderitem_and_more'),
        ('products', '0004_alter_product_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
