# Generated by Django 5.1.2 on 2024-11-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0002_rename_guest_pgroom_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('complaint', models.TextField(max_length=5000)),
            ],
        ),
    ]
