# Generated by Django 5.1.3 on 2024-12-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('FARMER', 'Farmer'), ('BUYER', 'Buyer')], max_length=10, null=True),
        ),
    ]
