# Generated by Django 5.1.3 on 2024-11-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_name_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='govt_id',
            field=models.ImageField(blank=True, default='', null=True, upload_to='photos/'),
        ),
    ]
