# Generated by Django 5.1.4 on 2025-01-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
